#!/usr/bin/env bash

BIN=/usr/local/bin

echo "Installing fcommit"
sudo curl -s https://raw.githubusercontent.com/gabrielmusskopf/fcommit/main/fcommit -o $BIN/fcommit && sudo chmod +x $BIN/fcommit
echo "fcommit successfully installed!"
